### ISSUE TITLE
Index is required

### ISSUE THREAD

**Issue by mhsafaeii** [PROaction/pytest-zephyr-scale-integration#2]
Hi
Thank you for developing a project
It worked for me with a few changes
I am writing about a problem I encountered here
In this function create_test_run_folder we need index overwise give a this message : "message": "Index is required"
to this body I added index and fix it
{
            "name": folder_name,
            "projectId": self.JIRA_PROJECT_ID,
            "index": 0
}

**Comment by SerSerPopov** [comment]
@mhsafaeii, Hi!

Thanks for the note. I fixed this in version 0.1.27 too.
